version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  storageDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  storageDBMigration:
    image: storagedbmigration
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDB

  admin:
    image: admin
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5001:5001"

  storekeeper:
    image: storekeeper
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5002:5002"

  buyer:
    image: buyer
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5003:5003"

  daemon:
    image: daemon
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration