version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redisDaemonNet
      - redisStorekeeperNet

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - adminerAuthNet
      - adminerStoreNet

  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - authNet
      - adminerAuthNet
    volumes:
      - authVolume:/var/lib/mysql

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDB
    networks:
      - authNet

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - "5000:5000"
    networks:
      - authNet

  storageDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - adminNet
      - adminerStoreNet
      - buyerNet
      - daemonNet
    volumes:
      - storageVolume:/var/lib/mysql

  storageDBMigration:
    image: storagedbmigration
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDB
    networks:
      - adminNet
      - buyerNet
      - daemonNet

  admin:
    image: admin
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5001:5001"
    networks:
      - adminNet

  storekeeper:
    image: storekeeper
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5002:5002"
    networks:
      - storekeeperNet
      - redisStorekeeperNet

  buyer:
    image: buyer
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    ports:
      - "5003:5003"
    networks:
      - buyerNet

  daemon:
    image: daemon
    environment:
      - DATABASE_URL = storageDB
      - REDIS_PORT = redis
    depends_on:
      - storageDBMigration
    networks:
      - daemonNet
      - redisDaemonNet



networks:

  adminerAuthNet:

  adminerStoreNet:

  authNet:

  adminNet:

  buyerNet:

  storekeeperNet:

  daemonNet:

  redisDaemonNet:

  redisStorekeeperNet:

volumes:

  authVolume:

  storageVolume:

